first_django_project/blog/urls.py
from django.urls import path 
from . import views # Use this for functions
from .views import HomeView, ArticleView, NewPostView # Use this for classes

app_name = 'blog'

urlpatterns = [
    #path('', views.home, name="home" ) 
    path('', HomeView.as_view(), name = "home"),
    path('article/<int:pk>', ArticleView.as_view(), name='article-detail'),
    path('postForm', NewPostView.as_view(), name='postForm'),
    path('base',views.base, name="base"),
]

first_django_project/core/urls.py
from django.urls import path 
from . import views
from .views import HomeView, ArticleView

app_name = 'core'

urlpatterns = [
    #path('', views.home, name="home" ) 
    path('', HomeView.as_view(), name = "home"),
    path('article/<int:pk>', ArticleView.as_view(), name='article-detail'),
    path('base',views.base, name="base"),
]

first_django_project/first_django/urls.py
from django.contrib import admin
from django.urls import path, include 

urlpatterns = [
    path('admin/', admin.site.urls),
    path('posts/', include('blog.urls',namespace='blog') ) 
]

first_django_project/blog/models.py
from django.db import models
from django.contrib.auth.models import User
# Create your models here.
class Post(models.Model):
    title = models.CharField(max_length=255)
    author = models.ForeignKey(User, on_delete=models.CASCADE)
    body = models.TextField()

    def __str__(self):
        return self.title + " | by " + str(self.author)
    

first_django_project/blog/views.py
from django.shortcuts import render
from django.views.generic import ListView, DetailView, CreateView
from .models import Post

# Class views
class HomeView(ListView):
    model = Post
    template_name = "posts/home.html"

class ArticleView(DetailView):
    model = Post
    template_name = "posts/article-detail.html"

class NewPostView(CreateView):
    model = Post
    template_name = 'posts/postForm.html'
    fields = dict.fromkeys(["title","author","body"])
    def addPost():
        pass

def base(request):
    return render(request,'base/base.html',{})

# Create your views here.

# Function Views
# def home(request):
#     return render(request,'home.html', {})

first_django_project/core/templates/article-detail.html
{% extends 'base/base.html'%}
{% block content %}

        <title>{{post.title}} | MyBlog</title>
        <div class="container-fluid">
            <div class="row block">
                <div class="col-md-12 post-body">
                    <h1>
                        {{post.title}}<span style="font-size: large; margin-left: 5%;" >By {{post.author}}</span>
                    </h1>
                    <hr>
                    <p>
                        {{ post.body }}
                    </p>
                    <a href="{% url 'core:home' %}">
                        <button type="button" class="btn btn-outline-dark" style=" color:
                            rgb(134, 172, 119); border: rgb(134, 172, 119) 3px;"> Go to Home </button>
                    </a>
                </div>
            </div>
        </div>

{% endblock %}

first_django_project/core/templates/base/base.html
<!doctype html>
<html lang="pt-br">
    <head>
        <!-- Required meta tags -->
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

        <!-- Bootstrap CSS -->
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css" integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk" crossorigin="anonymous">

        <style>
            .card a{
                color: rgb(134, 172, 119);
            }
            body{
                background-color: rgb(67, 73, 66);
                height: 100%;
            }
            .title{
                color: white;
            }
            footer{
                position:fixed;
                left: 0;
                bottom: 0;
                width: 100%;
                background-color: rgb(50, 52, 53);
                color: white;
                text-align: center;
                margin-top:4%;
            }
            .post-body{
                color:white;
            }
            .block{
                border-radius: 10px 10px 10px 10px;
                -moz-border-radius: 10px 10px 10px 10px;
                -webkit-border-radius: 10px 10px 10px 10px;
                border: 8px outset rgb(51, 57, 59);
                background-color:rgb(79, 88, 76);
                padding: 3%;
            }
            .push{
                height: 100%;
            }
        </style>
    </head>
    <body>
        <!-- Navbar -->
        <nav class="navbar navbar-expand-lg navbar-dark bg-dark" style="margin-bottom:1%;">
            <a class="navbar-brand" href="#">
                <img src="https://lh3.googleusercontent.com/proxy/Nswz8KFhqyEROl-sdraD-t7RiXcToUSa7hB4hjC_lHPtd6ZTbLkJUhZ-MqsudqFwQ5cO5CdyAc8WX87w1ZJl" style="width: 40px;">
                Django Blog
            </a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
                aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>

            <div class="collapse navbar-collapse" id="navbarSupportedContent">
                <ul class="navbar-nav mr-auto">
                    <li class="nav-item ">
                        <a class="nav-link" href=" {% url 'core:home'%}">Home</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'core:base' %}">Base</a>
                    </li>            
                </ul>
            </div>
        </nav>
        <!-- Main -->
        <div class="container-fluid">
            <div class="row">
                <div class="col-sm-2">
                </div>
                <div class="col-sm-8">            
        {% block content %}

        {% endblock %}
                </div>
                <div class="col-sm-2">
                </div>
            </div>
        </div>
        <div class="push"></div>
        <!-- Footer -->
        <footer class="footer mt-auto py-3">
            <div class="container">
                <span class="text-muted">Developed by <a href="https://github.com/Shaiene-kun" target="_blank">Shaiene-kun</a> and <a href="https://github.com/yasmin-liban" target="_blank">yasmin-liban</a> </span>
            </div>
        </footer>
        <!-- Optional JavaScript -->
        <!-- jQuery first, then Popper.js, then Bootstrap JS -->
        <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
        <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.min.js" integrity="sha384-OgVRvuATP1z7JjHLkuOU7Xw704+h835Lr+6QL9UvYjZE3Ipu6Tp75j7Bh/kR0JKI" crossorigin="anonymous"></script>    
  </body>
</html>

first_django_project/core/templates/home.html
{% extends 'base/base.html'%}
{% block content%}
        <h1 class="title" >Posts</h1>
        <div class="container-fluid">
            <div class="row">
                    
                    
                    {% for currentPost in object_list %}  


                        <div class="col-sm-6" style="padding:2%;">
                            <div class="card text-white bg-dark mb-3" style="height:100%; width:auto;">
                                <h5 class="card-header" >
                                    <a href="{% url 'core:article-detail' currentPost.pk %}" > <b> {{ currentPost.title }}</b> </a>
                                </h5>
                                <div class="card-body">                               
                                    <h6 class="card-subtitle mb-2 text-muted">
                                        by {{currentPost.author}}
                                    </h6>
                                    <p class="card-text">
                                        {{ currentPost.body }}
                                    </p>
                                </div>
                            </div>
                        </div>
                        <br>

                    {% endfor %}

            </div>
        </div>



            


    </body>
</html>
{% endblock %}

first_django_project/templates/base/base.html
<!doctype html>
<html lang="pt-br">
    <head>
        <!-- Required meta tags -->
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
        <title>Django App</title>
        <!-- Bootstrap CSS -->
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css" integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk" crossorigin="anonymous">

        <style>
            .card  a{
                color: rgb(134, 172, 119);
            }
            body{
                background-color: rgb(67, 73, 66);
                height: 100%;
            }
            .title{
                color: white;
            }
            footer{
                position:fixed;
                left: 0;
                bottom: 0;
                width: 100%;
                background-color: rgb(50, 52, 53);
                color: white;
                text-align: center;
                margin-top:4%;
            }
            .post-body{
                color:white;
            }
            .block{
                border-radius: 10px 10px 10px 10px;
                -moz-border-radius: 10px 10px 10px 10px;
                -webkit-border-radius: 10px 10px 10px 10px;
                border: 8px outset rgb(51, 57, 59);
                background-color:rgb(79, 88, 76);
                padding: 3%;
            }
            .push{
                height: 100%;
            }
            form label{
                font-size: x-large;
                color: white;
            }
        
        </style>
    </head>
    <body>
        <!-- Navbar -->
        <nav class="navbar navbar-expand-lg navbar-dark bg-dark" style="margin-bottom:1%;">
            <a class="navbar-brand" href="#">
                <img src="https://lh3.googleusercontent.com/proxy/Nswz8KFhqyEROl-sdraD-t7RiXcToUSa7hB4hjC_lHPtd6ZTbLkJUhZ-MqsudqFwQ5cO5CdyAc8WX87w1ZJl" style="width: 40px;">
                Django Blog
            </a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
                aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>

            <div class="collapse navbar-collapse" id="navbarSupportedContent">
                <ul class="navbar-nav mr-auto">
                    <li class="nav-item ">
                        <a class="nav-link" href=" {% url 'blog:home'%}">Home</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'blog:base' %}">Base</a>
                    </li>            
                </ul>
            </div>
        </nav>
        <!-- Main -->
        <div class="container-fluid">
            <div class="row">
                <div class="col-sm-2">
                </div>
                <div class="col-sm-8">            
        {% block content %}

        {% endblock %}
                </div>
                <div class="col-sm-2">
                </div>
            </div>
        </div>
        <div class="push"></div>
        <!-- Footer -->
        <footer class="footer mt-auto py-3">
            <div class="container">
                <span class="text-muted">Developed by <a href="https://github.com/Shaiene-kun" target="_blank">Shaiene-kun</a> and <a href="https://github.com/yasmin-liban" target="_blank">yasmin-liban</a> </span>
            </div>
        </footer>
        <!-- Optional JavaScript -->
        <!-- jQuery first, then Popper.js, then Bootstrap JS -->
        <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
        <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.min.js" integrity="sha384-OgVRvuATP1z7JjHLkuOU7Xw704+h835Lr+6QL9UvYjZE3Ipu6Tp75j7Bh/kR0JKI" crossorigin="anonymous"></script>    
  </body>
</html>

first_django_project/templates/posts/article-detail.html
{% extends 'base/base.html'%}
{% block content %}

        <title>{{post.title}} | MyBlog</title>
        <div class="container-fluid">
            <div class="row block">
                <div class="col-md-12 post-body">
                    <h1>
                        {{post.title}}<span style="font-size: large; margin-left: 5%;" >By {{post.author}}</span>
                    </h1>
                    <hr>
                    <p>
                        {{ post.body }}
                    </p>
                    <a href="{% url 'blog:home' %}">
                        <button type="button" class="btn btn-outline-dark" style=" color:
                            rgb(134, 172, 119); border: rgb(134, 172, 119) 3px;"> Go to Home </button>
                    </a>
                </div>
            </div>
        </div>

{% endblock %}

first_django_project/templates/posts/home.html
{% extends 'base/base.html'%}
{% block content%}

        <h1 class="title" >Posts</h1>
        <a href="{% url 'blog:postForm'%}">
            <button class="btn btn-sm btn-outline-light" > Write a new post </button>
        </a>

        <div class="container-fluid">
            <div class="row">
                    
                    
                    {% for currentPost in object_list %}  


                        <div class="col-sm-6" style="padding:2%;">
                            <div class="card text-white bg-dark mb-3" style="height:100%; width:auto;">
                                <h5 class="card-header" >
                                    <a href="{% url 'blog:article-detail' currentPost.pk %}" > <b> {{ currentPost.title }}</b> </a>
                                </h5>
                                <div class="card-body">                               
                                    <h6 class="card-subtitle mb-2 text-muted">
                                        by {{currentPost.author}}
                                    </h6>
                                    <p class="card-text">
                                        {{ currentPost.body }}
                                    </p>
                                </div>
                            </div>
                        </div>
                        <br>

                    {% endfor %}

            </div>
        </div>



            


    </body>
</html>
{% endblock %}

first_django_project/templates/posts/postForm.html
{% extends 'base/base.html' %}
{% block content %}

    <div class="row">
        <div class="col">
            <div class="card text-white bg-dark mb-3" style="height:100%; width:auto;">
                <h1 class="card-header"> Write a new post </h1>
                <div class="card-body">
                    <form method="GET">
                        {{ form.as_p }}
                        <input type="submit" value="Save">
                    </form>
                </div>
            </div>


        </div>
    </div>
    





   

{% endblock %}   